name: NDUltimateShop
version: 2.0.0
main: com.NguyenDevs.nDUltimateShop.NDUltimateShop
api-version: 1.16
depend: [Vault]
softdepend: [PlaceholderAPI]
author: NguyenDevs
description: Ultimate shop plugin with auction house, sell system, and black market

commands:
  ndshop:
    description: Main admin command
    usage: /ndshop <reload|shop|sell|coupon|nightshop>
    permission: ndshop.admin
    aliases: [shopadmin, ndus]

  shop:
    description: Open the shop GUI
    usage: /shop
    permission: ndshop.shop.use
    aliases: [cửahàng, ch, cuahang]

  ah:
    description: Open auction house or sell items
    usage: /ah [sell <price>]
    permission: ndshop.auction.use
    aliases: [auction, đấugiá, dg, daugia]

  sell:
    description: Open sell GUI
    usage: /sell
    permission: ndshop.sell.use
    aliases: [bán]

  nightshop:
    description: Open night shop
    usage: /nightshop
    permission: ndshop.nightshop.use
    aliases: [chợđêm, cd, ns, chodem]

  coupon:
    description: Use a coupon code
    usage: /coupon <code>
    permission: ndshop.coupon.use
    aliases: [giảmgiá, gg, code, giamgia]

permissions:
  ndshop.admin:
    description: Access to all admin commands
    default: op

  ndshop.shop.use:
    description: Access to shop
    default: true

  ndshop.auction.use:
    description: Access to auction house
    default: true

  ndshop.sell.use:
    description: Access to sell system
    default: true

  ndshop.nightshop.use:
    description: Access to night shop
    default: true

  ndshop.coupon.use:
    description: Use coupon codes
    default: true

  ndshop.*:
    description: All permissions
    default: op
    children:
      ndshop.admin: true
      ndshop.shop.use: true
      ndshop.auction.use: true
      ndshop.sell.use: true
      ndshop.nightshop.use: true
      ndshop.coupon.use: true