name: NDUltimateShop
version: 1.0.0
main: com.NguyenDevs.nDUltimateShop.NDUltimateShop
api-version: 1.20
depend: [Vault]
author: NguyenDevs
description: Ultimate shop plugin with auction, sell, coupons and night market

commands:
  shop:
    description: Mở cửa hàng
    permission: ndshop.shop.use
  auction:
    description: Mở nhà đấu giá
    aliases: [ah]
    permission: ndshop.auction.use
  sell:
    description: Mở giao diện bán vật phẩm
    permission: ndshop.sell.use
  coupon:
    description: Sử dụng mã giảm giá
    permission: ndshop.coupon.use
  blackshop:
    description: Mở chợ đêm
    permission: ndshop.blackshop.use
  ndshop:
    description: Lệnh admin
    permission: ndshop.admin

permissions:
  ndshop.admin:
    description: Quyền admin
    default: op
  ndshop.shop.use:
    description: Sử dụng cửa hàng
    default: true
  ndshop.auction.use:
    description: Sử dụng nhà đấu giá
    default: true
  ndshop.sell.use:
    description: Sử dụng giao diện bán
    default: true
  ndshop.coupon.use:
    description: Sử dụng mã giảm giá
    default: true
  ndshop.blackshop.use:
    description: Sử dụng chợ đêm
    default: true